to: 4.12.7
from: .*
url: https://issues.redhat.com/browse/OCPNODE-1502
name: LeakedMachineConfigBlocksMCO
fixedIn: 4.12.8
message: |-
  Machine Config Operator stalls when encountering orphaned KubeletConfig or ContainerRuntimeConfig resources.
matchingRules:
- type: Always

