to: 4.13.0-ec.4
from: .*
url: https://issues.redhat.com/browse/OCPNODE-1502
name: LeakedMachineConfigBlocksMCO
fixedIn: 4.13.0-rc.0
message: |-
  Machine Config Operator stalls when encountering orphaned KubeletConfig or ContainerRuntimeConfig resources.
matchingRules:
- type: Always

